uv run python -m analysis.sae_feature_saturation_effect \
  --data_dir data \
  --model_ckpt results/set_transformer/trial/best_model.pt \
  --sae_ckpt checkpoints/ST_encout_H256_D4096_topk_k16_lr0.0003_19999/sae.pt \
  --feature_id 3466 \
  --idx 377 \
  --split test \
  --token_idx -1 \
  --sat_value 10.0 \
  --out_dir sae_saturation_plots \
  --drop_others